### ISSUE TITLE
Missing filesystem permissions can cause a crash loop

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/prometheus-dirsize-exporter#5]
The dirsize exporter is crashing and restarting when it runs into a permission error. It would be good to document limitations around file system permissions making it robust enough to disregard them or similar instead of crashing.

This is from staging.2i2c.cloud, where it has been crashing for a while - but not that long.

```
kubectl get pods -n staging
shared-dirsize-metrics-5fbd66f5b6-j69ht   1/1     Running   11 (2m8s ago)   15d
```

```
kubectl logs -n staging shared-dirsize-metrics-5fbd66f5b6-j69ht --previous
Updated values for 0000-2d0002-2d8055-2d2870
Updated values for yuvipanda
Updated values for gmmw4cdxutpcydtmdolq7f56ks7ld6zy5y47ezplgmcmllibrzoa
Updated values for _shared
Updated values for erik-402i2c-2eorg
Updated values for g-3a108516754518362587599
Traceback (most recent call last):
  File "/usr/local/bin/dirsize-exporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 157, in main
    for subdir_info in walker.get_subdirs_info(args.parent_dir):
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 122, in get_subdirs_info
    yield self.get_dir_info(c)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 95, in get_dir_info
    dirinfo = self.get_dir_info(d)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 95, in get_dir_info
    dirinfo = self.get_dir_info(d)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 95, in get_dir_info
    dirinfo = self.get_dir_info(d)
              ^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 65, in get_dir_info
    for c in self.do_iops_action(os.listdir, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_dirsize_exporter/exporter.py", line 50, in do_iops_action
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/shared-volume/georgianaelena-402i2c-2eorg/georgianaelena-homedir/.local/share/jupyter/runtime'
```

**Comment by consideRatio** [comment]
@georgianaelena do you think this could have happened by working directly against your home folder as a root user or similar via the deployer, perhaps causing a file/directory there be owned by root etc?

**Comment by GeorgianaElena** [comment]
@consideRatio, I should have removed everything I had copied yesterday under the root user. Hope I've unblocked the dirsize exporter to do its job. Sorry for causing this :|

**Comment by consideRatio** [comment]
No worries at all @GeorgianaElena, I didn't mean to blame in any way - its great that we have discovered this and quickly understood how it can arise. I've seen other hubs with shared storage having issues, I wonder if users can end up causing this to happen themselves somehow.

**Comment by yuvipanda** [comment]
dirsize-exporter should definitely be fixed to handle these errors gracefully. `PermissionErrors` should probably result in the filesize to be marked as zero, although the other option is to try to run this as root (but with severely restricted permissions otherwise)
